# Generated by Django 3.2.9 on 2021-11-23 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_blogmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='BlogModel', # モデル名
            old_name='postdata',   # 変更前
            new_name='postdate'    # 変更後
        )
    ]
